// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meadow struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Trees []*Tree `json:"trees"`
}

type Mutation struct {
}

type NewMeadow struct {
	Name string `json:"name"`
}

type NewTree struct {
	Name     string `json:"name"`
	MeadowID string `json:"meadowID"`
}

type Query struct {
}

type Tree struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
